name: Manual Test - Discord Forex News (Firefox)

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set timezone to Asia/Singapore
        run: |
          sudo timedatectl set-timezone Asia/Singapore
          date  # show current system time

      - name: Install Chromium
        uses: browser-actions/setup-chrome@v2
        run: chrome --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          pip install requests beautifulsoup4 pytz selenium

      - name: Run script with Chrome
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python main.py
