name: Manual Test - Discord Forex News

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4 pytz selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run script with Selenium
        run: |
          export PATH=$PATH:/usr/bin/chromium-browser
          export CHROME_BIN=/usr/bin/chromium-browser
          python main.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
